export const INITIALIZE_CELLS = 'INITIALIZE_CELLS';
export const UPDATE_CELL_VALUE = 'UPDATE_CELL_VALUE';
export const EVALUATE_CELL = 'EVALUATE_CELL';
export const SET_UNSET_CURRENT_CELL = 'SET_UNSET_CURRENT_CELL';

export const ADD_ROW = 'ADD_ROW';
export const ADD_COLUMN = 'ADD_COLUMN';

export const UPDATE_CELL_FORMAT = 'UPDATE_CELL_FORMAT';

export const UNDO_ACTION = 'UNDO_ACTION';
export const REDO_ACTION = 'REDO_ACTION';
export const REMOVE_LAST_UNDO_ITEM = 'REMOVE_LAST_UNDO_ITEM';
export const REMOVE_LAST_REDO_ITEM = 'REMOVE_LAST_REDO_ITEM';
export const REPLACE_CELL = 'REPLACE_CELL';